### ISSUE TITLE
demoRedBall does not grasp the ball, and there is a big deviation from the exact position

### ISSUE THREAD

**Issue by linzdg** [robotology/icub-basic-demos#17]
demoRedBall does not grasp the ball accurately, and there is a big deviation from the exact position. However, iCubGui  showed icub could grasp the ball accurately. How to solve this problem?

And this is the gift:
![detail](https://user-images.githubusercontent.com/28899901/71566352-e4a93200-2af1-11ea-8d63-1e92606070fa.gif)

**Comment by pattacini** [comment]
Hi @linzdg

I'll try to assist you with this issue. 

Given the animation you have posted, it seems that the shape model used by the tracker does not reflect the actual red ball size you've been playing with.

The tracker, indeed, works in a single 2D image but then to extrapolate the 3D position of the ball needs to know its size. If the size is not correct, it very likely happens that iCub thinks the ball is further or closer than it is in reality.

To fix this, let me first have a glance at how the tracker processes the shape information. As this particular module is a contribution from another partner, it wasn't under our direct responsibility, historically. 

I'll get back to you as soon as I'll have streamlined these steps.
Stay tuned 👍

**Comment by pattacini** [comment]
Hi @linzdg

Here I am again to attempt to give you some guidance to fix this issue.

Let's go through the following steps 📝

### 🔽 Update the code
```sh
$ cd icub-basic-demos
$ git checkout master
$ git pull origin master --rebase
```

### ⚙ Install the latest configuration files
```sh
$ cd icub-basic-demos
$ mkdir -p build && cd build
$ cmake ..
$ make install 
```

### 🖊 Customize `pf3dTracker` configuration files
First, back up any current configuration files you may have already produced and then copy out the new configuration files where they can be edited safely:
```sh
$ cd ~/.local/share/yarp/contexts
$ if [ -d pf3Tracker ]; then cp -R pf3Tracker backup-pf3dTracker; fi
$ yarp-config context --import pf3dTracker
```

Generate the shape model relative to your specific ball:
```sh
$ cd ~/.local/share/yarp/contexts/pf3dTracker/models
$ python generate_shape_model.py --radius R
```
where `R` is the radius of your ball expressed in millimeters.

Update the `pf3dTracker` main configuration file to make it point at the new shape model:
```sh
$ cd ~/.local/share/yarp/contexts/pf3dTracker
$ sed -i "/^trackedObjectShapeTemplate/c\trackedObjectShapeTemplate models/shape_model.csv" pf3dTracker.ini
```

Finally, check that the file we have just edited will be loaded at startup by `pf3dTracker`:
```sh
$ yarp resource --context pf3dTracker --from pf3dTracker.ini
```
The last output line should report the path to the correct file.

### 🌀 Run the demo: first attempt
At this stage, you can give the demo the first try in order to verify that the ball will be now better localized in the 3D space, at least.

Very likely, the reaching will be still unprecise due to a number of impairments that are robot specific but that we can compensate for by fiddling with the options contained within the `demoRedBall` configuration file (refer to the next step).

### 🖊 Customize `demoRedBall` configuration files
As above, do:
```sh
$ cd ~/.local/share/yarp/contexts
$ if [ -d demoRedBall ]; then cp -R demoRedBall backup-demoRedBall; fi
$ yarp-config context --import demoRedBall
```

Edit the `demoRedBall` main configuration file `~/.local/share/yarp/contexts/demoRedBall/config.ini` and tune the following two options that are arm-specific and, as such, they are replicated twice under the two arm groups:
- `reach_offset`
    Represents the 3D offsets in `X Y Z` format that are further added up to the reaching position commanded to the arm. The coordinates are expressed in the root reference frame attached to the waist as per the figure displayed below.
- `grasp_offset`
    Represents the 3D offsets in `X Y Z` format that are further added up to the reaching when a grasping action is requested and are generally employed to push the hand firmly against the ball. The same reference frame of `reach_offset` is used here.

![root-reference-frame](https://user-images.githubusercontent.com/3738070/71623113-84da8600-2bda-11ea-8a7c-608e4f22ad1b.jpg)

### 🌀 Run the demo: iterative refinement
By adjusting the `reach_offset` and `grasp_offset` iteratively, one can converge to a condition where the robot can keep the ball correctly under target with its hand and grasp it successfully. 

Hope this helps.

**Comment by linzdg** [comment]
Thank you for your answer. I will follow your steps and let you know the result.

**Comment by linzdg** [comment]
I tried to run demoRedBall using icubSim. And I followed the steps below:
>yarpserver
>iCub_SIM
>yarprobotinterface --context simCartesianControl --config no_legs.xml
>iKinCartesianSolver --context simCartesianControl --part right_arm
>iKinCartesianSolver --context simCartesianControl --part left_arm
>iKinGazeCtrl --from configSim.ini
>iCubGui --xpos 800 --ypos 80 --width 370
which showed [ERROR]MultipleAnalogSensorsClient: Sensor of typr ThreeAxisLinearAccelerometers with index 0 has non-MAS_OK status.
>demoRedBall --from config-test.ini

>yarp connect /icubSim/inertial iCubGui/inertial:i
which showed failure: could not find destination port /iCubGui/inertial:i
>yarp connect /icubSim/head/state:o  /iCubGui/head:i                    success
>yarp connect /icubSim/torso/state:o /iCubGui/torso:i                    success
>yarp connect /icubSim/left_arm/state:o  /iCubGui/left_arm:i          success
>yarp connect /icubSim/right_arm/state:o /iCubGui/right_arm:i      success
>yarp connect /demoRedBall/gui:o /iCubGui/objects                       success

![e43fc39ff0a70e13b2b2e164f3a3124](https://user-images.githubusercontent.com/28899901/71802093-c4501900-3097-11ea-800e-84a41e9f53d6.jpg)

But how can I add the red ball in simulation? Or do I need install icub-tests?

**Comment by pattacini** [comment]
Hi @linzdg
 
You certainly need `icub-tests` for running the red-ball demo on the simulator. Anyway, the steps above are meant for adjusting the demo on the real robot, as the simulator is not affected by modeling impairments.

Given that our fixture on `icub-tests` for the red-ball demo is mainly used as an overall verification of the software, I don't think you can get anything particular by launching it. Therefore, my warm recommendation is to stick to real iCub.

**Comment by linzdg** [comment]
Thanks @pattacini
I want to  be familiar with the icubSim. Now I install robot-testing-framework and icub-tests. But when I 
>robottestingframework-testrunner --verbose --suite demoRedBall-icubSim.xml
It  showed:  cannot load plugin yarpmanager: error(foun): yarpmanager.so: cannot open shared objects file: No such file or directory

I found the same problem in https://github.com/robotology/icub-tests/issues/8
But it does not work.


the environment variable is below:
>export YARP_DATA_DIRS=/usr/local/share/yarp:/usr/local/share/iCub:/usr/local/share/ICUBcontrib:/home/lzd/icub-tests/suites
>export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/yarp
>export RobotTestingFramework_DIR=/home/lzd/robot-testing-framework/build
>export PATH=$PATH:$RobotTestingFramework_DIR/bin
>export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/lzd/icub-tests/build/plugins

**Comment by pattacini** [comment]
Hi @linzdg 

I can see that `LD_LIBRARY_PATH` is missing a piece; it should be rather something like this:
```sh
LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/yarp:/usr/local/lib/robottestingframework
```

As a general remark, let's try to be neat and keep herein only discussions related to the demo on the real robot. If you'd like to comment any further on `icub-tests`, please open a ticket therein instead.

**Comment by pattacini** [comment]
Closing, feel free to open it up again if/when needed.
