### ISSUE TITLE
CI Workflow fails

### ISSUE THREAD

**Issue by pattacini** [robotology/icub-basic-demos#41]
Similar to #40.
See https://github.com/robotology/icub-basic-demos/actions/workflows/ci.yml.

> [!note]
I've disabled the CI for the time being.

**Comment by traversaro** [comment]
At least for macOS, the failure is due to https://github.com/robotology/yarp/issues/2909 . In general, I personally stopped supporting homebrew in the robotology-superbuild in https://github.com/robotology/robotology-superbuild/pull/1407 for the reason discussed in https://github.com/robotology/robotology-superbuild/issues/842 . Unless someone really want to make sure homebrew works for some reasons, I would just suggest to drop the homebrew-based CI in icub-basic-demos.

**Comment by pattacini** [comment]
Totally agree 👍🏻

**Comment by Nicogene** [comment]
CI is now happy:
- https://github.com/robotology/icub-basic-demos/actions/runs/5963577821
