### ISSUE TITLE
CI Failure October 2023

### ISSUE THREAD

**Issue by Nicogene** [robotology/icub-basic-demos#44]
The CI is failing because boost seems not found.

- https://github.com/robotology/icub-basic-demos/actions/runs/6400697603/job/17374663057

What surprise me is that boost is used

https://github.com/search?q=repo%3Arobotology%2Ficub-basic-demos%20boost&type=code

But no `find_package(Boost)` is invoked

cc @traversaro @pattacini

**Comment by traversaro** [comment]
This is a gazebo-related regression. Basically since https://github.com/conda-forge/gazebo-feedstock/pull/190, gazebo stopped having a run dependency on the boost headers. This have been fixed in https://github.com/conda-forge/gazebo-feedstock/pull/191, packages for all platforms should be available as soon as the PR is merged and new packages are built (some hours for Windows as the compilation there is slow).

**Comment by Nicogene** [comment]
Now la CI is happy, closing:

- https://github.com/robotology/icub-basic-demos/actions/runs/6607856187
